<?php
// database/seeders/BplsOwnerSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\BplsOwner;

class BplsOwnerSeeder extends Seeder
{
    public function run(): void
    {
        $owners = [
            [
                'last_name' => 'Dela Cruz',
                'first_name' => 'Juan',
                'middle_name' => 'Santos',
                'citizenship' => 'Filipino',
                'civil_status' => 'Married',
                'gender' => 'Male',
                'birthdate' => '1985-03-15',
                'mobile_no' => '09171234567',
                'email' => 'juan.delacruz@email.com',
                'is_pwd' => false,
                'is_4ps' => false,
                'is_solo_parent' => false,
                'is_senior' => false,
                'discount_10' => false,
                'discount_5' => false,
                'region' => 'Region IV-A',
                'province' => 'Laguna',
                'municipality' => 'Santa Rosa',
                'barangay' => 'Balibago',
                'street' => '123 Rizal Street',
                'emergency_contact_person' => 'Maria Dela Cruz',
                'emergency_mobile' => '09179876543',
                'emergency_email' => 'maria.delacruz@email.com',
            ],
            [
                'last_name' => 'Reyes',
                'first_name' => 'Maria',
                'middle_name' => 'Garcia',
                'citizenship' => 'Filipino',
                'civil_status' => 'Single',
                'gender' => 'Female',
                'birthdate' => '1990-07-22',
                'mobile_no' => '09281234567',
                'email' => 'maria.reyes@email.com',
                'is_pwd' => false,
                'is_4ps' => true,
                'is_solo_parent' => true,
                'is_senior' => false,
                'discount_10' => true,
                'discount_5' => false,
                'region' => 'Region IV-A',
                'province' => 'Cavite',
                'municipality' => 'Bacoor',
                'barangay' => 'Habay',
                'street' => '45 Aguinaldo Highway',
                'emergency_contact_person' => 'Jose Reyes',
                'emergency_mobile' => '09281111111',
                'emergency_email' => 'jose.reyes@email.com',
            ],
            [
                'last_name' => 'Santos',
                'first_name' => 'Pedro',
                'middle_name' => 'Lim',
                'citizenship' => 'Filipino',
                'civil_status' => 'Married',
                'gender' => 'Male',
                'birthdate' => '1960-11-05',
                'mobile_no' => '09391234567',
                'email' => 'pedro.santos@email.com',
                'is_pwd' => false,
                'is_4ps' => false,
                'is_solo_parent' => false,
                'is_senior' => true,
                'discount_10' => false,
                'discount_5' => false,
                'region' => 'Region III',
                'province' => 'Bulacan',
                'municipality' => 'Malolos',
                'barangay' => 'Mojon',
                'street' => '78 MacArthur Highway',
                'emergency_contact_person' => 'Ana Santos',
                'emergency_mobile' => '09392222222',
                'emergency_email' => 'ana.santos@email.com',
            ],
            [
                'last_name' => 'Gonzales',
                'first_name' => 'Ana',
                'middle_name' => 'Cruz',
                'citizenship' => 'Filipino',
                'civil_status' => 'Widowed',
                'gender' => 'Female',
                'birthdate' => '1978-01-30',
                'mobile_no' => '09501234567',
                'email' => 'ana.gonzales@email.com',
                'is_pwd' => true,
                'is_4ps' => false,
                'is_solo_parent' => false,
                'is_senior' => false,
                'discount_10' => true,
                'discount_5' => false,
                'region' => 'NCR',
                'province' => 'Metro Manila',
                'municipality' => 'Quezon City',
                'barangay' => 'Batasan Hills',
                'street' => '12 Commonwealth Avenue',
                'emergency_contact_person' => 'Luis Gonzales',
                'emergency_mobile' => '09503333333',
                'emergency_email' => 'luis.gonzales@email.com',
            ],
            [
                'last_name' => 'Villanueva',
                'first_name' => 'Carlos',
                'middle_name' => 'Mendoza',
                'citizenship' => 'Filipino',
                'civil_status' => 'Single',
                'gender' => 'Male',
                'birthdate' => '1995-06-18',
                'mobile_no' => '09611234567',
                'email' => 'carlos.villanueva@email.com',
                'is_pwd' => false,
                'is_4ps' => false,
                'is_solo_parent' => false,
                'is_senior' => false,
                'discount_10' => false,
                'discount_5' => true,
                'region' => 'Region VII',
                'province' => 'Cebu',
                'municipality' => 'Cebu City',
                'barangay' => 'Lahug',
                'street' => '55 Gorordo Avenue',
                'emergency_contact_person' => 'Rosa Villanueva',
                'emergency_mobile' => '09614444444',
                'emergency_email' => 'rosa.villanueva@email.com',
            ],
        ];

        foreach ($owners as $owner) {
            BplsOwner::create($owner);
        }
    }
}