<?php
// database/migrations/2026_03_03_000001_add_business_id_to_bpls_business_entries.php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Add `business_id` to bpls_business_entries.
     *
     * Format (generated on Approve to Payment):
     *   {MUNICIPALITY_CODE}-{YEAR}-{ZERO_PADDED_ID}
     *   e.g.  MJY-2026-000029
     *
     * The actual value is generated by BusinessListController::approvePayment()
     * using the format stored in BplsSetting key: `business_id_format`
     * Default: {muni}-{year}-{id}
     *
     * Also adds walk_in_business_id to clients if not already present
     * (the column already exists per the SQL dump, so we guard with hasColumn).
     */
    public function up(): void
    {
        if (!Schema::hasColumn('bpls_business_entries', 'business_id')) {
            Schema::table('bpls_business_entries', function (Blueprint $table) {
                $table->string('business_id', 50)
                    ->nullable()
                    ->unique()
                    ->after('id')
                    ->comment('Generated on Approve to Payment. Format: {MUNI}-{YEAR}-{ID}');
            });
        }

        if (!Schema::hasColumn('clients', 'walk_in_business_id')) {
            Schema::table('clients', function (Blueprint $table) {
                $table->unsignedBigInteger('walk_in_business_id')
                    ->nullable()
                    ->after('id')
                    ->comment('Links client to their walk-in bpls_business_entry');

                $table->foreign('walk_in_business_id')
                    ->references('id')
                    ->on('bpls_business_entries')
                    ->nullOnDelete();
            });
        }
    }

    public function down(): void
    {
        if (Schema::hasColumn('bpls_business_entries', 'business_id')) {
            Schema::table('bpls_business_entries', function (Blueprint $table) {
                $table->dropUnique(['business_id']);
                $table->dropColumn('business_id');
            });
        }

        if (Schema::hasColumn('clients', 'walk_in_business_id')) {
            Schema::table('clients', function (Blueprint $table) {
                $table->dropForeign(['walk_in_business_id']);
                $table->dropColumn('walk_in_business_id');
            });
        }
    }
};